// Code generated by candi v1.8.18.

package main

import (
	"context"
	"time"

	"pkg.agungdp.dev/candi/config/database"
	"pkg.agungdp.dev/candi/config/env"

	_ "github.com/lib/pq"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
	defer cancel()

	env.Load("master-service")
	migrateMongo(ctx, database.InitMongoDB(ctx))
}
