// Code generated by candi v1.3.3.

package repository

import (
	"context"
	"database/sql"

	"pkg.agungdp.dev/candi/tracer"
)

type chatbotRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewChatbotRepoSQL mongo repo constructor
func NewChatbotRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) ChatbotRepository {
	return &chatbotRepoSQL{
		readDB, writeDB, tx,
	}
}

func (r *chatbotRepoSQL) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "ChatbotRepoSQL:FindHello")
	defer trace.Finish()

	return "Hello from repo sql layer", nil
}
