// Code generated by candi v1.3.1.

package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"

	"pkg.agungdwiprasetyo.com/candi/tracer"
)

type chatbotRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewChatbotRepoMongo mongo repo constructor
func NewChatbotRepoMongo(readDB, writeDB *mongo.Database) ChatbotRepository {
	return &chatbotRepoMongo{
		readDB, writeDB,
	}
}

func (r *chatbotRepoMongo) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "ChatbotRepoMongo:FindHello")
	defer trace.Finish()

	return "Hello from repo mongo layer", nil
}
