// Code generated by candi v1.3.1.

package workerhandler

import (
	"context"
	"time"

	"monorepo/services/auth-service/internal/modules/token/usecase"

	"pkg.agungdp.dev/candi/candishared"
	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// TaskQueueHandler struct
type TaskQueueHandler struct {
	uc        usecase.TokenUsecase
	validator interfaces.Validator
}

// NewTaskQueueHandler constructor
func NewTaskQueueHandler(uc usecase.TokenUsecase, validator interfaces.Validator) *TaskQueueHandler {
	return &TaskQueueHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *TaskQueueHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("token-task-one", h.taskOne)
	group.Add("token-task-two", h.taskTwo)
}

func (h *TaskQueueHandler) taskOne(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "TokenDeliveryTaskQueue:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	time.Sleep(100 * time.Millisecond)
	return &candishared.ErrorRetrier{
		Delay:   2 * time.Second,
		Message: "Error one",
	}
}

func (h *TaskQueueHandler) taskTwo(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "TokenDeliveryTaskQueue:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	return &candishared.ErrorRetrier{
		Delay:   3 * time.Second,
		Message: "Error two",
	}
}
