// Code generated by candi v1.8.18.

package graphqlhandler

import (
	"monorepo/services/master-service/internal/modules/apps/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
)

// GraphQLHandler model
type GraphQLHandler struct {
	mw        interfaces.Middleware
	uc        usecase.AppsUsecase
	validator interfaces.Validator
}

// NewGraphQLHandler delivery
func NewGraphQLHandler(mw interfaces.Middleware, uc usecase.AppsUsecase, validator interfaces.Validator) *GraphQLHandler {
	return &GraphQLHandler{
		mw: mw, uc: uc, validator: validator,
	}
}

// RegisterMiddleware register resolver based on schema in "api/graphql/*" path
func (h *GraphQLHandler) RegisterMiddleware(mwGroup *types.MiddlewareGroup) {
	mwGroup.Add("AppsQueryResolver.get_all", h.mw.GraphQLBearerAuth, h.mw.GraphQLPermissionACL("apps.getAllApps"))
	mwGroup.Add("AppsQueryResolver.get_me_permissions", h.mw.GraphQLBearerAuth)
	mwGroup.Add("AppsQueryResolver.get_all_me_apps", h.mw.GraphQLBearerAuth)
	mwGroup.Add("AppsMutationResolver.save", h.mw.GraphQLBearerAuth, h.mw.GraphQLPermissionACL("apps.addApps"))
	mwGroup.Add("AppsMutationResolver.save_permissions", h.mw.GraphQLBearerAuth)
}

// Query method
func (h *GraphQLHandler) Query() interface{} {
	return &queryResolver{root: h}
}

// Mutation method
func (h *GraphQLHandler) Mutation() interface{} {
	return &mutationResolver{root: h}
}

// Subscription method
func (h *GraphQLHandler) Subscription() interface{} {
	return &subscriptionResolver{root: h}
}
