// Code generated by candi v1.3.1.

package usecase

import (
	"context"
	"monorepo/services/storage-service/internal/modules/storage/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// StorageUsecase abstraction
type StorageUsecase interface {
	// add method
	Hello(ctx context.Context) string
	Upload(ctx context.Context, buff []byte, metadata *domain.UploadMetadata) <-chan candishared.Result
}
