// Code generated by candi v1.3.1.

package usecase

import (
	"context"
	"io"
	"monorepo/services/storage-service/internal/modules/storage/domain"
)

// StorageUsecase abstraction
type StorageUsecase interface {
	// add method
	Hello(ctx context.Context) string
	Upload(ctx context.Context, file io.Reader, metadata *domain.UploadMetadata) (err error)
}
