// Code generated by candi v1.3.1.

package graphqlhandler

import (
	"context"

	"monorepo/services/notification-service/internal/modules/push-notif/domain"

	"pkg.agungdp.dev/candi/candishared"
)

type subscriptionResolver struct {
	root *GraphQLHandler
}

func (s *subscriptionResolver) ListenTopic(ctx context.Context, input subscribeInputResolver) (<-chan *domain.Event, error) {

	tokenClaim := candishared.ParseTokenClaimFromContext(ctx)

	clientID := tokenClaim.Subject
	return s.root.uc.AddSubscriber(ctx, clientID, input.Topic), nil
}
