// Code generated by candi v1.3.1. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/mongo"
	tokenrepo "monorepo/services/auth-service/internal/modules/token/repository"
)

// RepoMongo uow
type RepoMongo struct {
	readDB, writeDB *mongo.Database

	// register all repository from modules
	TokenRepo tokenrepo.TokenRepository
}

var globalRepoMongo = new(RepoMongo)

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &RepoMongo{
		readDB: readDB, writeDB: writeDB,
		TokenRepo: tokenrepo.NewTokenRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() *RepoMongo {
	return globalRepoMongo
}
