// Code generated by candi v1.3.1.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/notification-service/internal/modules/push-notif/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// KafkaHandler struct
type KafkaHandler struct {
	uc        usecase.PushNotifUsecase
	validator interfaces.Validator
}

// NewKafkaHandler constructor
func NewKafkaHandler(uc usecase.PushNotifUsecase, validator interfaces.Validator) *KafkaHandler {
	return &KafkaHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *KafkaHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("push-notif", h.handlePushNotif) // handling topic "push-notif"
}

// ProcessMessage from kafka consumer
func (h *KafkaHandler) handlePushNotif(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "PushNotifDeliveryKafka:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Printf("message consumed by module push-notif. message: %s\n", string(message))
	h.uc.Hello(ctx)
	return nil
}
