// Code generated by candi v1.8.17.

package repository

import (
	"context"

	shareddomain "monorepo/services/auth-service/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// TokenRepository abstract interface
type TokenRepository interface {
	FetchAll(ctx context.Context, filter *candishared.Filter) ([]shareddomain.Token, error)
	Count(ctx context.Context, filter *candishared.Filter) int
	Find(ctx context.Context, data *shareddomain.Token) error
	Save(ctx context.Context, data *shareddomain.Token) error
}
