// Code generated by candi v1.3.1.

package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"

	"pkg.agungdwiprasetyo.com/candi/tracer"
)

type tokenRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewTokenRepoMongo mongo repo constructor
func NewTokenRepoMongo(readDB, writeDB *mongo.Database) TokenRepository {
	return &tokenRepoMongo{
		readDB, writeDB,
	}
}

func (r *tokenRepoMongo) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "TokenRepoMongo:FindHello")
	defer trace.Finish()

	return "Hello from repo mongo layer", nil
}
