// Code generated by candi v1.3.1.

package repository

import (
	"context"
)

// TokenRepository abstract interface
type TokenRepository interface {
	// add method
	FindHello(ctx context.Context) (string, error)
}
