// Code generated by candi v1.4.0.

package repository

import (
	"context"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"monorepo/services/master-service/internal/modules/apps/domain"
	shareddomain "monorepo/services/master-service/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candihelper"
	"pkg.agungdp.dev/candi/candishared"
	"pkg.agungdp.dev/candi/tracer"
)

type moduleRepoMongo struct {
	readDB, writeDB *mongo.Database
	collection      string
}

// NewModuleRepoMongo mongo repo constructor
func NewModuleRepoMongo(readDB, writeDB *mongo.Database) ModuleRepository {
	return &moduleRepoMongo{
		readDB, writeDB, "apps_modules",
	}
}

func (r *moduleRepoMongo) FetchAll(ctx context.Context, filter domain.FilterModule) (data []shareddomain.Module, err error) {
	trace := tracer.StartTrace(ctx, "ModuleRepoMongo:FetchAll")
	defer trace.Finish()
	defer func() { trace.SetError(err) }()
	ctx = trace.Context()

	findOptions := options.Find()
	if len(filter.OrderBy) > 0 {
		findOptions.SetSort(filter.OrderBy)
	}

	where := bson.M{}
	if filter.AppsID != "" {
		where["appsId"] = filter.AppsID
	}

	findOptions.SetLimit(int64(filter.Limit))
	findOptions.SetSkip(int64(filter.Offset))
	cur, err := r.readDB.Collection(r.collection).Find(ctx, where, findOptions)
	if err != nil {
		return nil, err
	}
	defer cur.Close(ctx)

	for cur.Next(ctx) {
		var app shareddomain.Module
		err := cur.Decode(&app)
		if err != nil {
			return data, err
		}
		app.CreatedAt = app.CreatedAtDB.Format(time.RFC3339)
		app.ModifiedAt = app.ModifiedAtDB.Format(time.RFC3339)
		data = append(data, app)
	}

	return
}

func (r *moduleRepoMongo) Count(ctx context.Context, filter candishared.Filter) int64 {
	trace := tracer.StartTrace(ctx, "ModuleRepoMongo:Count")
	defer trace.Finish()

	count, err := r.readDB.Collection(r.collection).CountDocuments(trace.Context(), bson.M{})
	trace.SetError(err)
	return count
}

func (r *moduleRepoMongo) GroupByApps(ctx context.Context, appsID ...string) (groups map[string][]shareddomain.Module) {
	trace := tracer.StartTrace(ctx, "ModuleRepoMongo:FetchAll")
	defer trace.Finish()
	ctx = trace.Context()

	groups = make(map[string][]shareddomain.Module)
	where := bson.M{
		"appsId": bson.M{
			"$in": appsID,
		},
	}
	cur, err := r.readDB.Collection(r.collection).Find(ctx, where)
	if err != nil {
		trace.SetError(err)
		return
	}
	defer cur.Close(ctx)

	for cur.Next(ctx) {
		var ep shareddomain.Module
		err := cur.Decode(&ep)
		if err != nil {
			trace.SetError(err)
			return
		}
		groups[ep.AppsID] = append(groups[ep.AppsID], ep)
	}

	return
}

func (r *moduleRepoMongo) Find(ctx context.Context, data *shareddomain.Module) (err error) {
	trace := tracer.StartTrace(ctx, "ModuleRepoMongo:Find")
	defer trace.Finish()
	defer func() { trace.SetError(err) }()
	ctx = trace.Context()

	bsonWhere := make(bson.M)
	if data.ID != "" {
		bsonWhere["_id"] = data.ID
	}
	if data.Code != "" {
		bsonWhere["code"] = data.Code
	}
	trace.SetTag("query", bsonWhere)

	return r.readDB.Collection(r.collection).FindOne(ctx, bsonWhere).Decode(data)
}

func (r *moduleRepoMongo) Save(ctx context.Context, data *shareddomain.Module) (err error) {
	trace := tracer.StartTrace(ctx, "ModuleRepoMongo:Count")
	defer trace.Finish()
	defer func() { trace.SetError(err) }()
	ctx = trace.Context()
	tracer.Log(ctx, "data", data)

	data.ModifiedAtDB = time.Now()
	if data.ID == "" {
		data.ID = primitive.NewObjectID().Hex()
		data.CreatedAtDB = time.Now()
		_, err = r.writeDB.Collection(r.collection).InsertOne(ctx, data)
	} else {
		opt := options.UpdateOptions{
			Upsert: candihelper.ToBoolPtr(true),
		}
		_, err = r.writeDB.Collection(r.collection).UpdateOne(ctx,
			bson.M{
				"_id": data.ID,
			},
			bson.M{
				"$set": data,
			}, &opt)
	}

	return
}
