// Code generated by candi v1.3.3.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/order-service/internal/modules/master/usecase"

	"pkg.agungdwiprasetyo.com/candi/codebase/factory/types"
	"pkg.agungdwiprasetyo.com/candi/codebase/interfaces"
	"pkg.agungdwiprasetyo.com/candi/tracer"
)

// KafkaHandler struct
type KafkaHandler struct {
	uc        usecase.MasterUsecase
	validator interfaces.Validator
}

// NewKafkaHandler constructor
func NewKafkaHandler(uc usecase.MasterUsecase, validator interfaces.Validator) *KafkaHandler {
	return &KafkaHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *KafkaHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("master", h.handleMaster) // handling topic "master"
}

// ProcessMessage from kafka consumer
func (h *KafkaHandler) handleMaster(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "MasterDeliveryKafka:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Printf("message consumed by module master. message: %s\n", string(message))
	h.uc.Hello(ctx)
	return nil
}
