// Code generated by candi v1.3.3.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/order-service/internal/modules/master/usecase"

	"pkg.agungdwiprasetyo.com/candi/codebase/factory/types"
	"pkg.agungdwiprasetyo.com/candi/codebase/interfaces"
	"pkg.agungdwiprasetyo.com/candi/tracer"
)

// RedisHandler struct
type RedisHandler struct {
	uc        usecase.MasterUsecase
	validator interfaces.Validator
}

// NewRedisHandler constructor
func NewRedisHandler(uc usecase.MasterUsecase, validator interfaces.Validator) *RedisHandler {
	return &RedisHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *RedisHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("master-sample", h.handleMaster)
}

func (h *RedisHandler) handleMaster(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "MasterDeliveryRedis:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Println("redis subs: execute sample")
	h.uc.Hello(ctx)
	return nil
}
