// Code generated by candi v1.4.0.

package graphqlhandler

import (
	"context"

	"pkg.agungdp.dev/candi/tracer"
)

type queryResolver struct {
	root *GraphQLHandler
}

// Hello resolver
func (q *queryResolver) Hello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "AclDeliveryGraphQL-Hello")
	defer trace.Finish()
	ctx = trace.Context()

	return "ok", nil
}
