// Code generated by candi v1.3.1.

package usecase

import (
	"context"
	"monorepo/services/auth-service/internal/modules/token/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// TokenUsecase abstraction
type TokenUsecase interface {
	Generate(ctx context.Context, payload *domain.Claim) (tokenString string, err error)
	Refresh(ctx context.Context, token string) <-chan candishared.Result
	Validate(ctx context.Context, tokenString string) (claim *domain.Claim, err error)
	Revoke(ctx context.Context, token string) <-chan candishared.Result
}
