// Code generated by candi v1.3.1.

package usecase

import (
	"context"
	"monorepo/services/auth-service/internal/modules/token/domain"

	"pkg.agungdwiprasetyo.com/candi/candishared"
)

// TokenUsecase abstraction
type TokenUsecase interface {
	Generate(ctx context.Context, payload *domain.Claim) <-chan candishared.Result
	Refresh(ctx context.Context, token string) <-chan candishared.Result
	Validate(ctx context.Context, token string) <-chan candishared.Result
	Revoke(ctx context.Context, token string) <-chan candishared.Result
}
