// Code generated by candi v1.3.3.

package repository

import (
	"context"
)

// OrderRepository abstract interface
type OrderRepository interface {
	// add method
	FindHello(ctx context.Context) (string, error)
}
