// Code generated by candi v1.3.3.

package repository

import (
	"context"
	"database/sql"

	"pkg.agungdwiprasetyo.com/candi/tracer"
)

type orderRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewOrderRepoSQL mongo repo constructor
func NewOrderRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) OrderRepository {
	return &orderRepoSQL{
		readDB, writeDB, tx,
	}
}

func (r *orderRepoSQL) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "OrderRepoSQL:FindHello")
	defer trace.Finish()

	return "Hello from repo sql layer", nil
}