// Code generated by candi v1.3.1.

package shared

// Environment additional in this service
type Environment struct {
	// more additional environment with struct tag is environment key example:
	// ExampleHost string `env:"EXAMPLE_HOST"`

	LineClientSecret string `env:"LINE_CLIENT_SECRET"`
	LineClientToken  string `env:"LINE_CLIENT_TOKEN"`
	ChatbotHost      string `env:"CHATBOT_HOST"`
	TranslatorHost   string `env:"TRANSLATOR_HOST"`
	TranslatorKey    string `env:"TRANSLATOR_KEY"`
}

var sharedEnv Environment

// GetEnv get global additional environment
func GetEnv() Environment {
	return sharedEnv
}

// SetEnv get global additional environment
func SetEnv(env Environment) {
	sharedEnv = env
}
