// Code generated by candi v1.3.3. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/mongo"
	masterrepo "monorepo/services/order-service/internal/modules/master/repository"
	orderrepo "monorepo/services/order-service/internal/modules/order/repository"
)

// RepoMongo uow
type RepoMongo struct {
	readDB, writeDB *mongo.Database

	// register all repository from modules
	MasterRepo masterrepo.MasterRepository
	OrderRepo orderrepo.OrderRepository
}

var globalRepoMongo = new(RepoMongo)

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &RepoMongo{
		readDB: readDB, writeDB: writeDB,
		MasterRepo: masterrepo.NewMasterRepoMongo(readDB, writeDB),
		OrderRepo: orderrepo.NewOrderRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() *RepoMongo {
	return globalRepoMongo
}
