// Code generated by candi v1.3.3.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/order-service/internal/modules/order/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// KafkaHandler struct
type KafkaHandler struct {
	uc        usecase.OrderUsecase
	validator interfaces.Validator
}

// NewKafkaHandler constructor
func NewKafkaHandler(uc usecase.OrderUsecase, validator interfaces.Validator) *KafkaHandler {
	return &KafkaHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *KafkaHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("order", h.handleOrder) // handling topic "order"
}

// ProcessMessage from kafka consumer
func (h *KafkaHandler) handleOrder(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "OrderDeliveryKafka:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Printf("message consumed by module order. message: %s\n", string(message))
	h.uc.Hello(ctx)
	return nil
}
