// Code generated by candi v1.3.3.

package repository

import (
	"context"
	"database/sql"

	"pkg.agungdp.dev/candi/tracer"
)

type memberRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewMemberRepoSQL mongo repo constructor
func NewMemberRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) MemberRepository {
	return &memberRepoSQL{
		readDB, writeDB, tx,
	}
}

func (r *memberRepoSQL) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "MemberRepoSQL:FindHello")
	defer trace.Finish()

	return "Hello from repo sql layer", nil
}
