// Code generated by candi v1.8.17.

package repository

import (
	"context"
	"errors"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candihelper"
	"pkg.agungdp.dev/candi/candishared"
	"pkg.agungdp.dev/candi/tracer"
)

type memberRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewMemberRepoMongo mongo repo constructor
func NewMemberRepoMongo(readDB, writeDB *mongo.Database) MemberRepository {
	return &memberRepoMongo{
		readDB: readDB, writeDB: writeDB,
	}
}

func (r *memberRepoMongo) FetchAll(ctx context.Context, filter *candishared.Filter) (data []shareddomain.Member, err error) {
	trace := tracer.StartTrace(ctx, "MemberRepoMongo:FetchAll")
	defer func() { trace.SetError(err); trace.Finish() }()
	ctx = trace.Context()

	query := bson.M{}
	findOptions := options.Find()
	if len(filter.OrderBy) > 0 {
		findOptions.SetSort(filter)
	}

	if !filter.ShowAll {
		findOptions.SetLimit(int64(filter.Limit))
		findOptions.SetSkip(int64(filter.Offset))
	}
	cur, err := r.readDB.Collection(shareddomain.Member{}.CollectionName()).Find(ctx, query, findOptions)
	if err != nil {
		return data, err
	}
	cur.All(ctx, &data)
	return
}

func (r *memberRepoMongo) Find(ctx context.Context, data *shareddomain.Member) (err error) {
	trace := tracer.StartTrace(ctx, "MemberRepoMongo:Find")
	defer func() { trace.SetError(err); trace.Finish() }()
	ctx = trace.Context()

	bsonWhere := make(bson.M)
	if data.ID != "" {
		bsonWhere["_id"] = data.ID
	}
	if data.Username != "" {
		bsonWhere["username"] = data.Username
	}

	if len(bsonWhere) == 0 {
		return errors.New("Data not found")
	}
	return r.readDB.Collection(data.CollectionName()).FindOne(ctx, bsonWhere).Decode(data)
}

func (r *memberRepoMongo) Count(ctx context.Context, filter *candishared.Filter) int {
	trace := tracer.StartTrace(ctx, "MemberRepoMongo:Count")
	defer trace.Finish()

	query := bson.M{}
	count, err := r.readDB.Collection(shareddomain.Member{}.CollectionName()).CountDocuments(ctx, query)
	trace.SetError(err)
	return int(count)
}

func (r *memberRepoMongo) Save(ctx context.Context, data *shareddomain.Member) (err error) {
	trace := tracer.StartTrace(ctx, "MemberRepoMongo:Save")
	defer func() { trace.SetError(err); trace.Finish() }()
	ctx = trace.Context()
	tracer.Log(ctx, "data", data)

	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	data.ModifiedAt = time.Now()

	if data.ID == "" {
		data.ID = primitive.NewObjectID().Hex()
		data.CreatedAt = time.Now()
		_, err = r.writeDB.Collection(data.CollectionName()).InsertOne(ctx, data)
	} else {
		opt := options.UpdateOptions{
			Upsert: candihelper.ToBoolPtr(true),
		}
		_, err = r.writeDB.Collection(data.CollectionName()).UpdateOne(ctx,
			bson.M{
				"_id": data.ID,
			},
			bson.M{
				"$set": data,
			}, &opt)
	}

	return
}
