// Code generated by candi v1.3.1.

package repository

import (
	"context"
	shareddomain "monorepo/services/user-service/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// MemberRepository abstract interface
type MemberRepository interface {
	FetchAll(ctx context.Context, filter candishared.Filter) ([]shareddomain.Member, error)
	Find(ctx context.Context, data *shareddomain.Member) (err error)
	Count(ctx context.Context, filter candishared.Filter) (count int64)
	Save(ctx context.Context, data *shareddomain.Member) (err error)
}
