// Code generated by candi v1.3.1.

package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"

	"pkg.agungdp.dev/candi/tracer"
)

type memberRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewMemberRepoMongo mongo repo constructor
func NewMemberRepoMongo(readDB, writeDB *mongo.Database) MemberRepository {
	return &memberRepoMongo{
		readDB, writeDB,
	}
}

func (r *memberRepoMongo) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "MemberRepoMongo:FindHello")
	defer trace.Finish()

	return "Hello from repo mongo layer", nil
}
