// Code generated by candi v1.3.1.

package repository

import (
	"context"
)

// MemberRepository abstract interface
type MemberRepository interface {
	// add method
	FindHello(ctx context.Context) (string, error)
}
