apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-line-chatbot
  labels:
    app: dev-line-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-line-chatbot
  template:
    metadata:
      labels:
        app: dev-line-chatbot
    spec:
      containers:
      - name: dev-line-chatbot
        image: line-chatbot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: dev-line-chatbot
spec:
  ports:
  - name: http
    targetPort: 8888
    port: 80
  selector:
    app: dev-line-chatbot

