// Code generated by candi v1.3.3.

package repository

import (
	"context"
	"database/sql"

	"pkg.agungdwiprasetyo.com/candi/tracer"
)

type eventRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewEventRepoSQL mongo repo constructor
func NewEventRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) EventRepository {
	return nil
}

func (r *eventRepoSQL) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "EventRepoSQL:FindHello")
	defer trace.Finish()

	return "Hello from repo sql layer", nil
}
