// Code generated by candi v1.3.1.

package repository

import (
	"context"
	"monorepo/services/line-chatbot/internal/modules/event/domain"

	"pkg.agungdwiprasetyo.com/candi/candishared"
)

// EventRepository abstract interface
type EventRepository interface {
	FindAll(ctx context.Context, filter *candishared.Filter) <-chan candishared.Result
	Count(ctx context.Context, filter *candishared.Filter) <-chan int
	Save(ctx context.Context, data *domain.Event) <-chan error
}
