// Code generated by candi v1.3.1.

package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"

	"pkg.agungdp.dev/candi/tracer"
)

type authRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewAuthRepoMongo mongo repo constructor
func NewAuthRepoMongo(readDB, writeDB *mongo.Database) AuthRepository {
	return &authRepoMongo{
		readDB, writeDB,
	}
}

func (r *authRepoMongo) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "AuthRepoMongo:FindHello")
	defer trace.Finish()

	return "Hello from repo mongo layer", nil
}
