// Code generated by candi v1.3.3.

package repository

import (
	"context"
	"database/sql"

	"pkg.agungdwiprasetyo.com/candi/tracer"
)

type masterRepoSQL struct {
	readDB, writeDB *sql.DB
	tx              *sql.Tx
}

// NewMasterRepoSQL mongo repo constructor
func NewMasterRepoSQL(readDB, writeDB *sql.DB, tx *sql.Tx) MasterRepository {
	return &masterRepoSQL{
		readDB, writeDB, tx,
	}
}

func (r *masterRepoSQL) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "MasterRepoSQL:FindHello")
	defer trace.Finish()

	return "Hello from repo sql layer", nil
}