// Code generated by candi v1.3.3.

package repository

import (
	"context"

	"go.mongodb.org/mongo-driver/mongo"

	"pkg.agungdp.dev/candi/tracer"
)

type masterRepoMongo struct {
	readDB, writeDB *mongo.Database
}

// NewMasterRepoMongo mongo repo constructor
func NewMasterRepoMongo(readDB, writeDB *mongo.Database) MasterRepository {
	return &masterRepoMongo{
		readDB, writeDB,
	}
}

func (r *masterRepoMongo) FindHello(ctx context.Context) (string, error) {
	trace := tracer.StartTrace(ctx, "MasterRepoMongo:FindHello")
	defer trace.Finish()

	return "Hello from repo mongo layer", nil
}
