// Code generated by candi v1.3.3.

package repository

import (
	"context"
)

// MasterRepository abstract interface
type MasterRepository interface {
	// add method
	FindHello(ctx context.Context) (string, error)
}
