// Code generated by candi v1.3.1. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/mongo"
	chatbotrepo "monorepo/services/line-chatbot/internal/modules/chatbot/repository"
	eventrepo "monorepo/services/line-chatbot/internal/modules/event/repository"
)

// RepoMongo uow
type RepoMongo struct {
	readDB, writeDB *mongo.Database

	// register all repository from modules
	ChatbotRepo chatbotrepo.ChatbotRepository
	EventRepo eventrepo.EventRepository
}

var globalRepoMongo = new(RepoMongo)

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &RepoMongo{
		readDB: readDB, writeDB: writeDB,
		ChatbotRepo: chatbotrepo.NewChatbotRepoMongo(readDB, writeDB),
		EventRepo: eventrepo.NewEventRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() *RepoMongo {
	return globalRepoMongo
}
