// Code generated by candi v1.3.1.

package repository

import (
	"context"
	"monorepo/services/notification-service/internal/modules/push-notif/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// PushNotifRepository abstract interface
type PushNotifRepository interface {
	// add method
	FindHello(ctx context.Context) (string, error)
	Save(ctx context.Context, data *domain.Topic) <-chan error
	FindTopic(ctx context.Context, where domain.Topic) <-chan candishared.Result
	RemoveSubscriber(ctx context.Context, subscriber *domain.Subscriber) <-chan error
	FindSubscriber(ctx context.Context, topicName string, subscriber *domain.Subscriber) <-chan candishared.Result
}
