// Code generated by candi v1.3.1.

package usecase

import (
	"context"
	"monorepo/services/notification-service/internal/modules/push-notif/domain"
	"time"
)

// PushNotifUsecase abstraction
type PushNotifUsecase interface {
	// add method
	Hello(ctx context.Context) string

	SendNotification(ctx context.Context, request *domain.PushNotifRequestPayload) error
	SendScheduledNotification(ctx context.Context, scheduledAt time.Time, request *domain.PushNotifRequestPayload) (err error)
	SendScheduledEvent(ctx context.Context, scheduledAt time.Time, request *domain.Event) (err error)

	PublishMessageToTopic(ctx context.Context, event *domain.Event) (*domain.Event, error)
	AddSubscriber(ctx context.Context, clientID, topic string) <-chan *domain.Event
}
