// Code generated by candi v1.3.1. DO NOT EDIT.

package repository

import (
	"go.mongodb.org/mongo-driver/mongo"
	aclrepo "monorepo/services/master-service/internal/modules/acl/repository"
	appsrepo "monorepo/services/master-service/internal/modules/apps/repository"
)

// RepoMongo uow
type RepoMongo struct {
	readDB, writeDB *mongo.Database

	// register all repository from modules
	AclRepo        aclrepo.AclRepository
	RoleRepo       aclrepo.RoleRepository
	AppsRepo       appsrepo.AppsRepository
	ModuleRepo     appsrepo.ModuleRepository
	PermissionRepo appsrepo.PermissionRepository
}

var globalRepoMongo = new(RepoMongo)

// setSharedRepoMongo set the global singleton "RepoMongo" implementation
func setSharedRepoMongo(readDB, writeDB *mongo.Database) {
	globalRepoMongo = &RepoMongo{
		readDB: readDB, writeDB: writeDB,
		AclRepo:        aclrepo.NewAclRepoMongo(readDB, writeDB),
		RoleRepo:       aclrepo.NewRoleRepoMongo(readDB, writeDB),
		AppsRepo:       appsrepo.NewAppsRepoMongo(readDB, writeDB),
		ModuleRepo:     appsrepo.NewModuleRepoMongo(readDB, writeDB),
		PermissionRepo: appsrepo.NewPermissionRepoMongo(readDB, writeDB),
	}
}

// GetSharedRepoMongo returns the global singleton "RepoMongo" implementation
func GetSharedRepoMongo() *RepoMongo {
	return globalRepoMongo
}
