apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-auth-service
  labels:
    app: dev-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth-service
  template:
    metadata:
      labels:
        app: dev-auth-service
    spec:
      containers:
      - name: dev-auth-service
        image: gcr.io/agungdp-218613/auth-service:latest
        ports:
          - containerPort: 8002
      imagePullSecrets: 
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: dev-auth-service
spec:
  type: LoadBalancer
  ports:
    - name: tcp-listener
      targetPort: 8002
      port: 80
      protocol: TCP
  selector:
    app: dev-auth-service

