apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-auth-service
  labels:
    app: dev-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-auth-service
  template:
    metadata:
      labels:
        app: dev-auth-service
    spec:
      containers:
        - name: dev-auth-service
          image: docker.io/agungdp22/auth-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dev-auth-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 80
  selector:
    app: dev-auth-service

