// Code generated by candi v1.4.0.

package workerhandler

import (
	"context"
	"time"

	"monorepo/services/user-service/internal/modules/member/usecase"

	"pkg.agungdp.dev/candi/candishared"
	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// TaskQueueHandler struct
type TaskQueueHandler struct {
	uc        usecase.MemberUsecase
	validator interfaces.Validator
}

// NewTaskQueueHandler constructor
func NewTaskQueueHandler(uc usecase.MemberUsecase, validator interfaces.Validator) *TaskQueueHandler {
	return &TaskQueueHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *TaskQueueHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("member-task-one", h.taskOne)
	group.Add("member-task-two", h.taskTwo)
}

func (h *TaskQueueHandler) taskOne(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "MemberDeliveryTaskQueue:TaskOne")
	defer trace.Finish()
	ctx = trace.Context()

	if string(message) == "no error" {
		return nil
	}

	return &candishared.ErrorRetrier{
		Delay:   10 * time.Second,
		Message: "Error one",
	}
}

func (h *TaskQueueHandler) taskTwo(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "MemberDeliveryTaskQueue:TaskTwo")
	defer trace.Finish()
	ctx = trace.Context()

	return &candishared.ErrorRetrier{
		Delay:   3 * time.Second,
		Message: "Error two",
	}
}
