// Code generated by candi v1.4.0.

package usecase

import (
	"context"
	"monorepo/services/master-service/internal/modules/acl/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// ACLUsecase abstraction
type ACLUsecase interface {
	// add method
	Hello(ctx context.Context) string
	SaveRole(ctx context.Context, payload domain.AddRoleRequest) (resp domain.RoleResponse, err error)
	GrantUser(ctx context.Context, payload domain.GrantUserRequest) (err error)
	CheckPermission(ctx context.Context, userID string, permissionCode string) (err error)
	GetAllRole(ctx context.Context, filter domain.RoleListFilter) ([]domain.RoleResponse, candishared.Meta, error)
	GetDetailRole(ctx context.Context, roleID string) (data domain.RoleResponse, err error)
}
