// Code generated by candi v1.4.0.

package usecase

import (
	"context"
	"monorepo/services/master-service/internal/modules/acl/domain"
	shareddomain "monorepo/services/master-service/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// ACLUsecase abstraction
type ACLUsecase interface {
	// add method
	Hello(ctx context.Context) string
	SaveRole(ctx context.Context, payload domain.AddRoleRequest) (resp domain.AddRoleResponse, err error)
	GrantUser(ctx context.Context, payload domain.GrantUserRequest) (err error)
	CheckPermission(ctx context.Context, payload domain.CheckPermissionRequest) (err error)
	GetAllRole(ctx context.Context, filter domain.RoleListFilter) ([]shareddomain.Role, candishared.Meta, error)
}
