// Code generated by candi v1.8.18.

package usecase

import (
	"context"
	"monorepo/services/master-service/internal/modules/acl/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// ACLUsecase abstraction
type ACLUsecase interface {
	SaveRole(ctx context.Context, payload domain.AddRoleRequest) (resp domain.RoleResponse, err error)
	GrantUser(ctx context.Context, payload domain.GrantUserRequest) (err error)
	CheckPermission(ctx context.Context, userID string, permissionCode string) (role string, err error)
	GetAllRole(ctx context.Context, filter domain.RoleListFilter) ([]domain.RoleResponse, candishared.Meta, error)
	GetDetailRole(ctx context.Context, roleID string) (data domain.RoleResponse, err error)
	RevokeUserRole(ctx context.Context, userID, roleID string) (err error)
}
