// Code generated by candi v1.4.0.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/master-service/internal/modules/acl/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// RedisHandler struct
type RedisHandler struct {
	uc        usecase.ACLUsecase
	validator interfaces.Validator
}

// NewRedisHandler constructor
func NewRedisHandler(uc usecase.ACLUsecase, validator interfaces.Validator) *RedisHandler {
	return &RedisHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *RedisHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("acl-sample", h.handleACL)
}

func (h *RedisHandler) handleACL(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "AclDeliveryRedis:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Println("redis subs: execute sample")
	return nil
}
