// Code generated by candi v1.4.0.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/master-service/internal/modules/apps/usecase"

	"pkg.agungdp.dev/candi/candihelper"
	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// CronHandler struct
type CronHandler struct {
	uc        usecase.AppsUsecase
	validator interfaces.Validator
}

// NewCronHandler constructor
func NewCronHandler(uc usecase.AppsUsecase, validator interfaces.Validator) *CronHandler {
	return &CronHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *CronHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add(candihelper.CronJobKeyToString("apps-scheduler", "10s"), h.handleApps)
}

func (h *CronHandler) handleApps(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "AppsDeliveryCron:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Println("cron: execute in module apps")
	return nil
}
