// Code generated by candi v1.4.0.

package workerhandler

import (
	"context"
	"fmt"

	"monorepo/services/master-service/internal/modules/apps/usecase"

	"pkg.agungdp.dev/candi/codebase/factory/types"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
)

// KafkaHandler struct
type KafkaHandler struct {
	uc        usecase.AppsUsecase
	validator interfaces.Validator
}

// NewKafkaHandler constructor
func NewKafkaHandler(uc usecase.AppsUsecase, validator interfaces.Validator) *KafkaHandler {
	return &KafkaHandler{
		uc:        uc,
		validator: validator,
	}
}

// MountHandlers mount handler group
func (h *KafkaHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	group.Add("apps", h.handleApps) // handling topic "apps"
}

// ProcessMessage from kafka consumer
func (h *KafkaHandler) handleApps(ctx context.Context, message []byte) error {
	trace := tracer.StartTrace(ctx, "AppsDeliveryKafka:Hello")
	defer trace.Finish()
	ctx = trace.Context()

	fmt.Printf("message consumed by module apps. message: %s\n", string(message))
	return nil
}
