// Code generated by candi v1.8.17.

package graphqlhandler

import "context"

type subscriptionResolver struct {
	root *GraphQLHandler
}

// Hello resolver
func (s *subscriptionResolver) Hello(ctx context.Context) <-chan string {
	output := make(chan string)

	go func() {
		output <- "Hello from Member"
	}()

	return output
}
