// Code generated by candi v1.3.1.

package usecase

import (
	"sync"
	storageusecase "monorepo/services/storage-service/internal/modules/storage/usecase"

	"pkg.agungdwiprasetyo.com/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		Storage() storageusecase.StorageUsecase
	}

	usecaseUow struct {
		storage storageusecase.StorageUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = &usecaseUow{
			storage: storageusecase.NewStorageUsecase(deps),
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}
func (uc *usecaseUow) Storage() storageusecase.StorageUsecase {
	return uc.storage
}
