name: Development

on:
  push:
    tags: [ dev/auth-service, dev/storage-service ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test service=${GITHUB_REF#refs/tags/dev/}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      run: |
        make prepare service=${GITHUB_REF#refs/tags/dev/}
        make docker service=${GITHUB_REF#refs/tags/dev/}
        docker tag ${GITHUB_REF#refs/tags/dev/} docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF#refs/tags/dev/}:latest
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REF#refs/tags/dev/}:latest
