name: Go

on:
  push:
    tags: [ dev/auth-service ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test service=auth-service

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      run: |
        make prepare service=auth-service
        make docker service=auth-service
        docker tag auth-service docker.io/agungdp22/auth-service:latest
        docker push docker.io/agungdp22/auth-service:latest
