name: Go

on:
  push:
    tags: [ dev/auth-service ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: make test service=auth-service

    - name: Build
      run: |
        make prepare service=auth-service
        make docker service=auth-service
